# Generated by Django 5.1.4 on 2025-04-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_frist_db_asset_management_edit_phone_field_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcustomuser',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='Phone Number'),
        ),
    ]
