# Generated by Django 5.1.4 on 2025-04-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_frist_db_asset_management_edit_phone_field_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblassetsmanagement',
            name='serial_asset',
            field=models.TextField(max_length=250, verbose_name='Serial Asset'),
        ),
    ]
