# Generated by Django 5.1.4 on 2025-04-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_frist_db_asset_management_edit_serial_number_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBrandCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand_category', models.CharField(max_length=250, verbose_name='Name Brand')),
            ],
            options={
                'verbose_name': 'Brand Category',
                'verbose_name_plural': 'Brand Categories',
            },
        ),
        migrations.AddField(
            model_name='tblassetsmanagement',
            name='name_brand_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblbrandcategories', verbose_name='Name Brand Category'),
        ),
    ]
